### ISSUE TITLE
Error `Cannot read property 'replace' of null `

### ISSUE THREAD

**Issue by ehmicky** [daviddarnes/netlify-plugin-ghost-markdown#7]
The following error happened in one build:

```
Cannot read property 'replace' of null 
    /opt/buildhome/.netlify-build-plugins/node_modules/netlify-plugin-ghost-markdown/index.js:88:19 formatImagePaths
    /opt/buildhome/.netlify-build-plugins/node_modules/netlify-plugin-ghost-markdown/index.js:120:7 createMarkdownContent
    /opt/buildhome/.netlify-build-plugins/node_modules/netlify-plugin-ghost-markdown/index.js:395:22 
    /opt/buildhome/.netlify-build-plugins/node_modules/netlify-plugin-ghost-markdown/index.js:288:5 async onPreBuild
    src/plugins/child/run.js:15:3 async Object.run
    src/plugins/child/main.js:34:38 async handleEvent
    src/plugins/ipc.js:101:9 async process.<anonymous>
```

It appears that one of the pages returned by `api.pages.browse()` had its `html` attribute `null`.

Full deploy logs:

```
7:56:32 PM: Build ready to start
7:59:03 PM: build-image version: 3031d4c9e432fd7016f6279fc9ad706f9205d845
7:59:03 PM: build-image tag: v3.3.17
7:59:03 PM: buildbot version: d2dce75b20e52883432aefbd693a7ea0140bb7af
7:59:03 PM: Fetching cached dependencies
7:59:03 PM: Failed to fetch cache, continuing with build
7:59:03 PM: Starting to prepare the repo for build
7:59:03 PM: No cached dependencies found. Cloning fresh repo
7:59:03 PM: git clone https://github.com/AlanChatfield/www2.alanchatfield.net
7:59:04 PM: Preparing Git Reference refs/heads/master
7:59:05 PM: Starting build script
7:59:06 PM: Installing dependencies
7:59:06 PM: Python version set to 2.7
7:59:07 PM: Downloading and installing node v8.17.0...
7:59:07 PM: Downloading https://nodejs.org/dist/v8.17.0/node-v8.17.0-linux-x64.tar.xz...
7:59:08 PM: Computing checksum with sha256sum
7:59:08 PM: Checksums matched!
7:59:10 PM: Now using node v8.17.0 (npm v6.13.4)
7:59:10 PM: Started restoring cached build plugins
7:59:10 PM: Finished restoring cached build plugins
7:59:10 PM: Attempting ruby version 2.3.6, read from environment
7:59:11 PM: 
7:59:11 PM: ** WARNING **
7:59:11 PM: Using custom ruby version 2.3.6, this will slow down the build.
7:59:11 PM: To ensure fast builds, set the RUBY_VERSION environment variable, or .ruby-version file, to an included ruby version.
7:59:11 PM: Included versions: 2.7.1 2.6.2
7:59:11 PM: 
7:59:11 PM: Required ruby-2.3.6 is not installed - installing.
7:59:12 PM: Searching for binary rubies, this might take some time.
7:59:12 PM: Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/16.04/x86_64/ruby-2.3.6.tar.bz2
7:59:12 PM: Checking requirements for ubuntu.
7:59:12 PM: Requirements installation successful.
7:59:13 PM: ruby-2.3.6 - #configure
7:59:13 PM: ruby-2.3.6 - #download
7:59:14 PM: ruby-2.3.6 - #validate archive
7:59:24 PM: ruby-2.3.6 - #extract
7:59:31 PM: ruby-2.3.6 - #validate binary
7:59:32 PM: ruby-2.3.6 - #setup
7:59:32 PM: ruby-2.3.6 - #gemset created /opt/buildhome/.rvm/gems/ruby-2.3.6@global
7:59:34 PM: ruby-2.3.6 - #importing gemset /opt/buildhome/.rvm/gemsets/global.gems............................................................
7:59:35 PM: ruby-2.3.6 - #generating global wrappers.......
7:59:35 PM: ruby-2.3.6 - #gemset created /opt/buildhome/.rvm/gems/ruby-2.3.6
7:59:35 PM: ruby-2.3.6 - #importing gemsetfile /opt/buildhome/.rvm/gemsets/default.gems evaluated to empty gem list
7:59:35 PM: ruby-2.3.6 - #generating default wrappers.......
7:59:35 PM: Using /opt/buildhome/.rvm/gems/ruby-2.3.6
7:59:36 PM: Using ruby version 2.3.6
7:59:36 PM: Using PHP version 5.6
7:59:36 PM: 5.2 is already installed.
7:59:36 PM: Using Swift version 5.2
7:59:36 PM: Started restoring cached node modules
7:59:36 PM: Finished restoring cached node modules
7:59:36 PM: Installing NPM modules using NPM version 6.13.4
7:59:37 PM: npm notice created a lockfile as package-lock.json. You should commit this file.
7:59:37 PM: npm WARN alanchatfield.net@1.0.0 No description
7:59:38 PM: up to date in 0.533s
7:59:38 PM: found 0 vulnerabilities
7:59:38 PM: NPM modules installed
7:59:38 PM: Installing Hugo 0.71.1
7:59:40 PM: Hugo Static Site Generator v0.71.1-A301F6B2/extended linux/amd64 BuildDate: 2020-05-25T09:18:12Z
7:59:40 PM: Started restoring cached go cache
7:59:40 PM: Finished restoring cached go cache
7:59:40 PM: Installing Go version 1.10
7:59:49 PM: unset GOOS;
7:59:49 PM: unset GOARCH;
7:59:49 PM: export GOROOT='/opt/buildhome/.gimme_cache/versions/go1.10.linux.amd64';
7:59:49 PM: export PATH="/opt/buildhome/.gimme_cache/versions/go1.10.linux.amd64/bin:${PATH}";
7:59:49 PM: go version >&2;
7:59:49 PM: export GIMME_ENV="/opt/buildhome/.gimme_cache/env/go1.10.linux.amd64.env"
7:59:49 PM: go version go1.10 linux/amd64
7:59:49 PM: Installing missing commands
7:59:49 PM: Verify run directory
7:59:51 PM: ​
7:59:51 PM: ┌─────────────────────────────┐
7:59:51 PM: │        Netlify Build        │
7:59:51 PM: └─────────────────────────────┘
7:59:51 PM: ​
7:59:51 PM: ❯ Version
7:59:51 PM:   @netlify/build 2.0.10
7:59:51 PM: ​
7:59:51 PM: ❯ Flags
7:59:51 PM:   deployId: 5ef0f0d0fe16a600075e8a02
7:59:51 PM:   mode: buildbot
7:59:51 PM: ​
7:59:51 PM: ❯ Current directory
7:59:51 PM:   /opt/build/repo
7:59:51 PM: ​
7:59:51 PM: ❯ Config file
7:59:51 PM:   /opt/build/repo/netlify.toml
7:59:51 PM: ​
7:59:51 PM: ❯ Context
7:59:51 PM:   production
7:59:51 PM: ​
7:59:51 PM: ❯ Loading plugins
7:59:51 PM:    - netlify-plugin-hugo-cache-resources@0.1.4 from Netlify app
7:59:51 PM:    - netlify-plugin-ghost-markdown@2.1.0 from netlify.toml
7:59:51 PM: ​
7:59:51 PM: ┌────────────────────────────────────────────────────────────────┐
7:59:51 PM: │ 1. onPreBuild command from netlify-plugin-hugo-cache-resources │
7:59:51 PM: └────────────────────────────────────────────────────────────────┘
7:59:51 PM: ​
7:59:51 PM: No cache found for resources folder
7:59:51 PM: ​
7:59:51 PM: (netlify-plugin-hugo-cache-resources onPreBuild completed in 222ms)
7:59:51 PM: ​
7:59:51 PM: ┌──────────────────────────────────────────────────────────┐
7:59:51 PM: │ 2. onPreBuild command from netlify-plugin-ghost-markdown │
7:59:51 PM: └──────────────────────────────────────────────────────────┘
7:59:51 PM: ​
7:59:51 PM: No cache file found
7:59:53 PM: ​
7:59:53 PM: ┌───────────────────────────────────────────────────────┐
7:59:53 PM: │ Plugin "netlify-plugin-ghost-markdown" internal error │
7:59:53 PM: └───────────────────────────────────────────────────────┘
7:59:53 PM: ​
7:59:53 PM:   Error message
7:59:53 PM:   TypeError: Cannot read property 'replace' of null
7:59:53 PM: ​
7:59:53 PM:   Plugin details
7:59:53 PM:   Package:        netlify-plugin-ghost-markdown
7:59:53 PM:   Version:        2.1.0
7:59:53 PM:   Repository:     git://github.com/daviddarnes/netlify-plugin-ghost-markdown.git
7:59:53 PM:   npm link:       https://www.npmjs.com/package/netlify-plugin-ghost-markdown
7:59:53 PM:   Report issues:  https://github.com/daviddarnes/netlify-plugin-ghost-markdown/issues
7:59:53 PM: ​
7:59:53 PM:   Error location
7:59:53 PM:   In "onPreBuild" event in "netlify-plugin-ghost-markdown" from netlify.toml
7:59:53 PM:       at formatImagePaths (/opt/buildhome/.netlify-build-plugins/node_modules/netlify-plugin-ghost-markdown/index.js:88:19)
7:59:53 PM:       at createMarkdownContent (/opt/buildhome/.netlify-build-plugins/node_modules/netlify-plugin-ghost-markdown/index.js:120:7)
7:59:53 PM:       at /opt/buildhome/.netlify-build-plugins/node_modules/netlify-plugin-ghost-markdown/index.js:395:22
7:59:53 PM:       at async Promise.all (index 172)
7:59:53 PM:       at async onPreBuild (/opt/buildhome/.netlify-build-plugins/node_modules/netlify-plugin-ghost-markdown/index.js:288:5)
7:59:53 PM:       at async Object.run (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/run.js:15:3)
7:59:53 PM:       at async handleEvent (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/main.js:34:38)
7:59:53 PM:       at async process.<anonymous> (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/ipc.js:101:9)
7:59:53 PM: ​
7:59:53 PM:   Resolved config
7:59:53 PM:   build:
7:59:53 PM:     command: hugo
7:59:53 PM:     publish: /opt/build/repo/public
7:59:53 PM:   plugins:
7:59:53 PM:     - inputs: {}
7:59:53 PM:       origin: ui
7:59:53 PM:       package: netlify-plugin-hugo-cache-resources
7:59:53 PM:     - inputs:
7:59:53 PM:         postDatePrefix: false
7:59:53 PM:       origin: config
7:59:53 PM:       package: netlify-plugin-ghost-markdown
7:59:53 PM: Caching artifacts
7:59:53 PM: Started saving node modules
7:59:53 PM: Finished saving node modules
7:59:53 PM: Started saving build plugins
7:59:53 PM: Finished saving build plugins
7:59:53 PM: Started saving pip cache
8:00:01 PM: Finished saving pip cache
8:00:01 PM: Started saving emacs cask dependencies
8:00:01 PM: Finished saving emacs cask dependencies
8:00:01 PM: Started saving maven dependencies
8:00:01 PM: Finished saving maven dependencies
8:00:01 PM: Started saving boot dependencies
8:00:01 PM: Finished saving boot dependencies
8:00:01 PM: Started saving go dependencies
8:00:04 PM: Finished saving go dependencies
8:00:08 PM: Cached ruby version 2.3.6
8:00:08 PM: Error running command: Build script returned non-zero exit code: 1
8:00:08 PM: Failing build: Failed to build site
8:00:08 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
8:00:08 PM: Finished processing build request in 1m5.314059793s
```

The repository and commit was [this one](https://github.com/AlanChatfield/www2.alanchatfield.net/commit/9574f5b772c2e3272975f1a034a43b21c95ecd38).

**Comment by daviddarnes** [comment]
Thanks for the report @ehmicky, has this been happening more recently? There's some changes happening in the Ghost API and I'm waiting for it to be stable before updating.

**Comment by ehmicky** [comment]
No, it only happened once, 3 weeks ago.

**Comment by daviddarnes** [comment]
I'll leave this open in case you see it happen again. Thanks for reporting 😊

**Comment by ehmicky** [comment]
This happened again. Unfortunately, the site was deleted, so I do not have access to additional information :-/

**Comment by daviddarnes** [comment]
Ah damn, thanks for reporting though @ehmicky. So I guess this has only happened twice?

**Comment by ehmicky** [comment]
Yes, only twice.

**Comment by daviddarnes** [comment]
Cool, thanks for reporting. I think it must be the API content that's coming down, something is either malformed or not what I was expecting. Next time is comes up would it be possible to contact the original user? Maybe they can share their steps?
